.unbackground $2ca4 $2cc5
.unbackground $2d50 $2d5d
.unbackground $5fdf $5fe3
.unbackground $1d398 $1d3a0
.unbackground $1d3a1 $1d3a8
.unbackground $1d3a9 $1d3b4
.unbackground $1d3b5 $1d3be
.unbackground $1d3bf $1d3d7
.unbackground $1d3d8 $1d3e0
.unbackground $1d3e1 $1d3e9
.unbackground $1d3ea $1d3f0
.unbackground $1d3f1 $1d3fa
.unbackground $1d3fb $1d403
.unbackground $1d404 $1d411
.unbackground $1d412 $1d417
.unbackground $1d418 $1d41d
.unbackground $1d41e $1d427
.unbackground $1d428 $1d42d
.unbackground $1d42e $1d438
.unbackground $1d439 $1d490
.unbackground $1d491 $1d4ef
.unbackground $1d4f0 $1d4fd
.unbackground $1d4fe $1d50e
.unbackground $1d50f $1d519
.unbackground $1d51a $1d521
.unbackground $1d522 $1d56a
.unbackground $1d56b $1d5b5
.unbackground $1d5b6 $1d60e
.unbackground $1d60f $1d667
.unbackground $1d668 $1d670
.unbackground $1d671 $1d67e
.unbackground $1da14 $1da1c
.unbackground $1da1d $1da25
.unbackground $1da26 $1da2d
.unbackground $1da2e $1da39
.unbackground $1da3a $1da43
.unbackground $1da5e $1da95
.unbackground $1da96 $1dacd
.unbackground $1dace $1db15
.unbackground $1db16 $1db5f
.unbackground $1db60 $1dba7
.unbackground $1dba8 $1dbec
.unbackground $1dbed $1dc36
.unbackground $1dc37 $1dc78
.unbackground $1dc79 $1dcbf
.unbackground $1dcc0 $1dd08
.unbackground $1dd09 $1dd51
.unbackground $1dd52 $1dd96
.unbackground $1dd97 $1dde1
.unbackground $1dde2 $1dde7
.unbackground $1dde8 $1ddf5
.unbackground $1ddf6 $1de30
.unbackground $1de3b $1de6f
.unbackground $1de70 $1dea1
.unbackground $1dea2 $1dee3
.unbackground $1dee4 $1df1c
.section "Script2ca4" free
Script2ca4: .db "Hello world!", $ff, $ff, $fd, "!", $fe
.ends
.section "Script2d50" free
Script2d50: .db "Hello world!", $fe
.ends
.section "Script5fdf" free
Script5fdf: .db "Hello world!", $fe
.ends
.section "Script1d398" free
Script1d398: .db "Hello world!", $fe
.ends
.section "Script1d3a1" free
Script1d3a1: .db "Hello world!", $fe
.ends
.section "Script1d3a9" free
Script1d3a9: .db "Hello world!", $fe
.ends
.section "Script1d3b5" free
Script1d3b5: .db "Hello world!", $fe
.ends
.section "Script1d3bf" free
Script1d3bf: .db "Hello world!", $fe
.ends
.section "Script1d3d8" free
Script1d3d8: .db "Hello world!", $fe
.ends
.section "Script1d3e1" free
Script1d3e1: .db "Hello world!", $fe
.ends
.section "Script1d3ea" free
Script1d3ea: .db "Hello world!", $fe
.ends
.section "Script1d3f1" free
Script1d3f1: .db "Hello world!", $fe
.ends
.section "Script1d3fb" free
Script1d3fb: .db "Hello world!", $fe
.ends
.section "Script1d404" free
Script1d404: .db "Hello world!", $fe
.ends
.section "Script1d412" free
Script1d412: .db "Hello world!", $fe
.ends
.section "Script1d418" free
Script1d418: .db "Hello world!", $fe
.ends
.section "Script1d41e" free
Script1d41e: .db "Hello world!", $fe
.ends
.section "Script1d428" free
Script1d428: .db "Hello world!", $fe
.ends
.section "Script1d42e" free
Script1d42e: .db "Hello world!", $fe
.ends
.section "Script1d439" free
Script1d439: .db "Hello world!", $fe
.ends
.section "Script1d491" free
Script1d491: .db "Hello world!", $fe
.ends
.section "Script1d4f0" free
Script1d4f0: .db "Hello world!", $fe
.ends
.section "Script1d4fe" free
Script1d4fe: .db "Hello world!", $fe
.ends
.section "Script1d50f" free
Script1d50f: .db "Hello world!", $fe
.ends
.section "Script1d51a" free
Script1d51a: .db "Hello world!", $fe
.ends
.section "Script1d522" free
Script1d522: .db "Hello world!", $fe
.ends
.section "Script1d56b" free
Script1d56b: .db "Hello world!", $fe
.ends
.section "Script1d5b6" free
Script1d5b6: .db "Hello world!", $fe
.ends
.section "Script1d60f" free
Script1d60f: .db "Hello world!", $fe
.ends
.section "Script1d668" free
Script1d668: .db "Hello world!", $fe
.ends
.section "Script1d671" free
Script1d671: .db "Hello world!", $fe
.ends
.section "Script1da14" free
Script1da14: .db "Hello world!", $fe
.ends
.section "Script1da1d" free
Script1da1d: .db "Hello world!", $fe
.ends
.section "Script1da26" free
Script1da26: .db "Hello world!", $fe
.ends
.section "Script1da2e" free
Script1da2e: .db "Hello world!", $fe
.ends
.section "Script1da3a" free
Script1da3a: .db "Hello world!", $fe
.ends
.section "Script1da5e" free
Script1da5e: .db "Hello world!", $fe
.ends
.section "Script1da96" free
Script1da96: .db "Hello world!", $fe
.ends
.section "Script1dace" free
Script1dace: .db "Hello world!", $fe
.ends
.section "Script1db16" free
Script1db16: .db "Hello world!", $fe
.ends
.section "Script1db60" free
Script1db60: .db "Hello world!", $fe
.ends
.section "Script1dba8" free
Script1dba8: .db "Hello world!", $fe
.ends
.section "Script1dbed" free
Script1dbed: .db "Hello world!", $fe
.ends
.section "Script1dc37" free
Script1dc37: .db "Hello world!", $fe
.ends
.section "Script1dc79" free
Script1dc79: .db "Hello world!", $fe
.ends
.section "Script1dcc0" free
Script1dcc0: .db "Hello world!", $fe
.ends
.section "Script1dd09" free
Script1dd09: .db "Hello world!", $fe
.ends
.section "Script1dd52" free
Script1dd52: .db "Hello world!", $fe
.ends
.section "Script1dd97" free
Script1dd97: .db "Hello world!", $fe
.ends
.section "Script1dde2" free
Script1dde2: .db "Hello world!", $fe
.ends
.section "Script1dde8" free
Script1dde8: .db "Hello world!", $fe
.ends
.section "Script1ddf6" free
Script1ddf6: .db "Hello world!", $fe
.ends
.section "Script1de3b" free
Script1de3b: .db "Hello world!", $fe
.ends
.section "Script1de70" free
Script1de70: .db "Hello world!", $fe
.ends
.section "Script1dea2" free
Script1dea2: .db "Hello world!", $fe
.ends
.section "Script1dee4" free
Script1dee4: .db "Hello world!", $fe
.ends
.bank 0 slot 0
.orga $2d2e
.section "Patch at 2d2e" overwrite
.dw Script2ca4
.ends
.bank 0 slot 0
.orga $2d36
.section "Patch at 2d36" overwrite
.dw Script2d50
.ends
.bank 0 slot 0
.orga $2d3e
.section "Patch at 2d3e" overwrite
.dw Script1dde2
.ends
.bank 0 slot 0
.orga $2d46
.section "Patch at 2d46" overwrite
.dw Script1dde8
.ends
.bank 0 slot 0
.orga $2d4e
.section "Patch at 2d4e" overwrite
.dw Script1ddf6
.ends
.bank 7 slot 2
.org $1e31
.section "Patch at 1de31" overwrite
.dw Script1de3b
.ends
.bank 7 slot 2
.org $1e33
.section "Patch at 1de33" overwrite
.dw Script1de70
.ends
.bank 7 slot 2
.org $1e35
.section "Patch at 1de35" overwrite
.dw Script1dea2
.ends
.bank 7 slot 2
.org $1e37
.section "Patch at 1de37" overwrite
.dw Script1dee4
.ends
.bank 7 slot 2
.org $1e39
.section "Patch at 1de39" overwrite
.dw Script1db16
.ends
.bank 7 slot 2
.org $1a44
.section "Patch at 1da44" overwrite
.dw Script1da5e
.ends
.bank 7 slot 2
.org $1a46
.section "Patch at 1da46" overwrite
.dw Script1da96
.ends
.bank 7 slot 2
.org $1a48
.section "Patch at 1da48" overwrite
.dw Script1dace
.ends
.bank 7 slot 2
.org $1a4a
.section "Patch at 1da4a" overwrite
.dw Script1db16
.ends
.bank 7 slot 2
.org $1a4c
.section "Patch at 1da4c" overwrite
.dw Script1db60
.ends
.bank 7 slot 2
.org $1a4e
.section "Patch at 1da4e" overwrite
.dw Script1dbed
.ends
.bank 7 slot 2
.org $1a50
.section "Patch at 1da50" overwrite
.dw Script1dc37
.ends
.bank 7 slot 2
.org $1a52
.section "Patch at 1da52" overwrite
.dw Script1dcc0
.ends
.bank 7 slot 2
.org $1a54
.section "Patch at 1da54" overwrite
.dw Script1dd52
.ends
.bank 7 slot 2
.org $1a56
.section "Patch at 1da56" overwrite
.dw Script1dba8
.ends
.bank 7 slot 2
.org $1a58
.section "Patch at 1da58" overwrite
.dw Script1dc79
.ends
.bank 7 slot 2
.org $1a5a
.section "Patch at 1da5a" overwrite
.dw Script1dd09
.ends
.bank 7 slot 2
.org $1a5c
.section "Patch at 1da5c" overwrite
.dw Script1dd97
.ends
.bank 0 slot 0
.orga $5866
.section "Patch at 5866" overwrite
.dw Script1da14
.ends
.bank 0 slot 0
.orga $586a
.section "Patch at 586a" overwrite
.dw Script1da1d
.ends
.bank 0 slot 0
.orga $586e
.section "Patch at 586e" overwrite
.dw Script1da26
.ends
.bank 0 slot 0
.orga $5872
.section "Patch at 5872" overwrite
.dw Script1da2e
.ends
.bank 0 slot 0
.orga $5876
.section "Patch at 5876" overwrite
.dw Script1da3a
.ends
.bank 7 slot 2
.org $1fb5
.section "Patch at 1dfb5" overwrite
.dw Script1d398
.ends
.bank 7 slot 2
.org $1fb9
.section "Patch at 1dfb9" overwrite
.dw Script1d522
.ends
.bank 7 slot 2
.org $1fbd
.section "Patch at 1dfbd" overwrite
.dw Script1d3a1
.ends
.bank 7 slot 2
.org $1fc1
.section "Patch at 1dfc1" overwrite
.dw Script1d56b
.ends
.bank 7 slot 2
.org $1fc5
.section "Patch at 1dfc5" overwrite
.dw Script1d3a9
.ends
.bank 7 slot 2
.org $1fc9
.section "Patch at 1dfc9" overwrite
.dw Script1d5b6
.ends
.bank 7 slot 2
.org $1fcd
.section "Patch at 1dfcd" overwrite
.dw Script1d3b5
.ends
.bank 7 slot 2
.org $1fd1
.section "Patch at 1dfd1" overwrite
.dw Script1d60f
.ends
.bank 7 slot 2
.org $1fe0
.section "Patch at 1dfe0" overwrite
.dw Script1d3d8
.ends
.bank 7 slot 2
.org $1fe4
.section "Patch at 1dfe4" overwrite
.dw Script1d3ea
.ends
.bank 7 slot 2
.org $1fe8
.section "Patch at 1dfe8" overwrite
.dw Script1d3e1
.ends
.bank 7 slot 2
.org $1fec
.section "Patch at 1dfec" overwrite
.dw Script1d3bf
.ends
.bank 7 slot 2
.org $1ff1
.section "Patch at 1dff1" overwrite
.dw Script1d3ea
.ends
.bank 7 slot 2
.org $1ff5
.section "Patch at 1dff5" overwrite
.dw Script1d3f1
.ends
.bank 7 slot 2
.org $1ff9
.section "Patch at 1dff9" overwrite
.dw Script1d3bf
.ends
.bank 7 slot 2
.org $1ffe
.section "Patch at 1dffe" overwrite
.dw Script1d3fb
.ends
.bank 7 slot 2
.org $2002
.section "Patch at 1e002" overwrite
.dw Script1d3ea
.ends
.bank 7 slot 2
.org $2006
.section "Patch at 1e006" overwrite
.dw Script1d3bf
.ends
.bank 7 slot 2
.org $200b
.section "Patch at 1e00b" overwrite
.dw Script1d404
.ends
.bank 7 slot 2
.org $200f
.section "Patch at 1e00f" overwrite
.dw Script1d404
.ends
.bank 7 slot 2
.org $2013
.section "Patch at 1e013" overwrite
.dw Script1d404
.ends
.bank 7 slot 2
.org $2017
.section "Patch at 1e017" overwrite
.dw Script1d3bf
.ends
.bank 7 slot 2
.org $201c
.section "Patch at 1e01c" overwrite
.dw Script1d3fb
.ends
.bank 7 slot 2
.org $2020
.section "Patch at 1e020" overwrite
.dw Script1d412
.ends
.bank 7 slot 2
.org $2024
.section "Patch at 1e024" overwrite
.dw Script1d418
.ends
.bank 7 slot 2
.org $2028
.section "Patch at 1e028" overwrite
.dw Script1d3bf
.ends
.bank 7 slot 2
.org $203e
.section "Patch at 1e03e" overwrite
.dw Script1d41e
.ends
.bank 7 slot 2
.org $2042
.section "Patch at 1e042" overwrite
.dw Script1d428
.ends
.bank 7 slot 2
.org $2046
.section "Patch at 1e046" overwrite
.dw Script1d42e
.ends
.bank 7 slot 2
.org $204a
.section "Patch at 1e04a" overwrite
.dw Script1d439
.ends
.bank 7 slot 2
.org $204e
.section "Patch at 1e04e" overwrite
.dw Script1d491
.ends
.bank 7 slot 2
.org $2052
.section "Patch at 1e052" overwrite
.dw Script1d4f0
.ends
.bank 7 slot 2
.org $2056
.section "Patch at 1e056" overwrite
.dw Script1d4fe
.ends
.bank 7 slot 2
.org $205a
.section "Patch at 1e05a" overwrite
.dw Script1d50f
.ends
.bank 7 slot 2
.org $205e
.section "Patch at 1e05e" overwrite
.dw Script1d51a
.ends
.bank 0 slot 0
.orga $5e55
.section "Patch at 5e55" overwrite
.dw Script1d668
.ends
.bank 0 slot 0
.orga $5ea1
.section "Patch at 5ea1" overwrite
.dw Script1d671
.ends
.bank 0 slot 0
.orga $5fa2
.section "Patch at 5fa2" overwrite
.dw Script5fdf
.ends
