.unbackground $2ca4 $2cc5
.unbackground $2d50 $2d5d
.unbackground $5c0c $5c22
.unbackground $5fdf $5fe3
.unbackground $1d398 $1d3a0
.unbackground $1d3a1 $1d3a8
.unbackground $1d3a9 $1d3b4
.unbackground $1d3b5 $1d3be
.unbackground $1d3bf $1d3d7
.unbackground $1d3d8 $1d3e0
.unbackground $1d3e1 $1d3e9
.unbackground $1d3ea $1d3f0
.unbackground $1d3f1 $1d3fa
.unbackground $1d3fb $1d403
.unbackground $1d404 $1d411
.unbackground $1d412 $1d417
.unbackground $1d418 $1d41d
.unbackground $1d41e $1d427
.unbackground $1d428 $1d42d
.unbackground $1d42e $1d438
.unbackground $1d439 $1d490
.unbackground $1d491 $1d4ef
.unbackground $1d4f0 $1d4fd
.unbackground $1d4fe $1d50e
.unbackground $1d50f $1d519
.unbackground $1d51a $1d521
.unbackground $1d522 $1d56a
.unbackground $1d56b $1d5b5
.unbackground $1d5b6 $1d60e
.unbackground $1d60f $1d667
.unbackground $1d668 $1d670
.unbackground $1d671 $1d67e
.unbackground $1da14 $1da1c
.unbackground $1da1d $1da25
.unbackground $1da26 $1da2d
.unbackground $1da2e $1da39
.unbackground $1da3a $1da43
.unbackground $1da5e $1da95
.unbackground $1da96 $1dacd
.unbackground $1dace $1db15
.unbackground $1db16 $1db5f
.unbackground $1db60 $1dba7
.unbackground $1dba8 $1dbec
.unbackground $1dbed $1dc36
.unbackground $1dc37 $1dc78
.unbackground $1dc79 $1dcbf
.unbackground $1dcc0 $1dd08
.unbackground $1dd09 $1dd51
.unbackground $1dd52 $1dd96
.unbackground $1dd97 $1dde1
.unbackground $1dde2 $1dde7
.unbackground $1dde8 $1ddf5
.unbackground $1ddf6 $1de30
.unbackground $1de3b $1de6f
.unbackground $1de70 $1dea1
.unbackground $1dea2 $1dee3
.unbackground $1dee4 $1df1c
.bank 0 slot 0
.section "Script2ca4" free
Script2ca4: .asc "Please choose.", $ff, $ff, $fd, "        Car", $ff, $ff, $ff, "        Motorcycle", $fe
.ends
.bank 0 slot 0
.section "Script2d50" free
Script2d50: .asc "This is the end of the game.", $fe
.ends
.bank 0 slot 0
.section "Script5c0c" free
Script5c0c: .asc "Genten    points  Mochiten   points"
.ends
.bank 0 slot 0
.section "Script5fdf" free
Script5fdf: .asc "Cause", $fe
.ends
.bank 7 slot 2
.section "Script1d398" free
Script1d398: .asc " Driving Eye ", $fe
.ends
.bank 7 slot 2
.section "Script1d3a1" free
Script1d3a1: .asc " Speed sense ", $fe
.ends
.bank 7 slot 2
.section "Script1d3a9" free
Script1d3a9: .asc " Driving technique ", $fe
.ends
.bank 7 slot 2
.section "Script1d3b5" free
Script1d3b5: .asc " Risk Control ", $fe
.ends
.bank 7 slot 2
.section "Script1d3bf" free
Script1d3bf: .asc "When you are ready to", $ff, "start, press   .", $fe
.ends
.bank 7 slot 2
.section "Script1d3d8" free
Script1d3d8: .asc "Selection button", $fe
.ends
.bank 7 slot 2
.section "Script1d3e1" free
Script1d3e1: .asc "Submit button", $fe
.ends
.bank 7 slot 2
.section "Script1d3ea" free
Script1d3ea: .asc "Not used", $fe
.ends
.bank 7 slot 2
.section "Script1d3f1" free
Script1d3f1: .asc "Use the net", $fe
.ends
.bank 7 slot 2
.section "Script1d3fb" free
Script1d3fb: .asc "Steering", $fe
.ends
.bank 7 slot 2
.section "Script1d404" free
Script1d404: .asc "I'll let you know if the worm is out.", $fe
.ends
.bank 7 slot 2
.section "Script1d412" free
Script1d412: .asc "Brake", $fe
.ends
.bank 7 slot 2
.section "Script1d418" free
Script1d418: .asc "Accelerate", $fe
.ends
.bank 7 slot 2
.section "Script1d41e" free
Script1d41e: .asc "Please press   .", $fe
.ends
.bank 7 slot 2
.section "Script1d428" free
Script1d428: .asc "Practice", $fe
.ends
.bank 7 slot 2
.section "Script1d42e" free
Script1d42e: .asc "Start the test", $fe
.ends
.bank 7 slot 2
.section "Script1d439" free
Script1d439: .asc "Pyon Kichi-kun goes to", $fd, "Pyonko's house to play. In", $fd, "Tochiyu, I do various", $fd, "things. At that time, what", $fd, "did Pyeong Kichi-kun take?", $fe
.ends
.bank 7 slot 2
.section "Script1d491" free
Script1d491: .asc "Your money is 100. If you", $fd, "wake up, you will be", $fd, "overwhelmed, and the game", $fd, "will be over if you lose", $fd, "the garbage. Please keep", $fd, "your goal and protect your", $fd, "goal.", $fe
.ends
.bank 7 slot 2
.section "Script1d4f0" free
Script1d4f0: .asc "You have done.", $fe
.ends
.bank 7 slot 2
.section "Script1d4fe" free
Script1d4fe: .asc "You have caused.", $fe
.ends
.bank 7 slot 2
.section "Script1d50f" free
Script1d50f: .asc "Start the game.", $fe
.ends
.bank 7 slot 2
.section "Script1d51a" free
Script1d51a: .asc "Game over", $fe
.ends
.bank 7 slot 2
.section "Script1d522" free
Script1d522: .asc "This is a test to see how", $ff, "well you can identify", $ff, "fast-moving objects.", $fd, "Please tell us what is going", $ff, "past the window.", $fe
.ends
.bank 7 slot 2
.section "Script1d56b" free
Script1d56b: .asc "This is a test of your", $ff, "ability to judge speed.", $fd, "Please catch the animals.", $fe
.ends
.bank 7 slot 2
.section "Script1d5b6" free
Script1d5b6: .asc "This is a test of your", $ff, "ability to navigate through", $ff, "traffic.", $fd, "Please follow the", $ff, "motorcycle.", $fe
.ends
.bank 7 slot 2
.section "Script1d60f" free
Script1d60f: .asc "This is a test of your", $ff, "ability to identify and", $ff, "react.", $fd, "Please press the buttons", $ff, "according to the colors of", $ff, "the flags.", $fe
.ends
.bank 7 slot 2
.section "Script1d668" free
Script1d668: .asc "Well done.", $fe
.ends
.bank 7 slot 2
.section "Script1d671" free
Script1d671: .asc "Good luck.", $fe
.ends
.bank 7 slot 2
.section "Script1da14" free
Script1da14: .asc "Sose Seki", $fe
.ends
.bank 7 slot 2
.section "Script1da1d" free
Script1da1d: .asc "Driving Eye", $fe
.ends
.bank 7 slot 2
.section "Script1da26" free
Script1da26: .asc "Speed ​​sense", $fe
.ends
.bank 7 slot 2
.section "Script1da2e" free
Script1da2e: .asc "Driving technique", $fe
.ends
.bank 7 slot 2
.section "Script1da3a" free
Script1da3a: .asc "Risk control", $fe
.ends
.bank 7 slot 2
.section "Script1da5e" free
Script1da5e: .asc "Your driving sense is very", $fd, "good.", $fd, "Let's get to the heart of this", $fd, "work.", $fe
.ends
.bank 7 slot 2
.section "Script1da96" free
Script1da96: .asc "Your driving sense is good.", $fd, "From now on, let's keep trying", $fd, "to keep up.", $fe
.ends
.bank 7 slot 2
.section "Script1dace" free
Script1dace: .asc "This is your driving sense.", $fd, "From now on, let's keep on", $fd, "going for speed and energy.", $fe
.ends
.bank 7 slot 2
.section "Script1db16" free
Script1db16: .asc "You may have a problem that is", $fd, "easy to get hot or hurry, so", $fd, "let your heart settle down", $fd, "from the bottom of your heart,", $fd, "and try to keep your feelings", $fd, "in good shape.", $fe
.ends
.bank 7 slot 2
.section "Script1db60" free
Script1db60: .asc "You will need to take one out", $fd, "of every two hours, as you", $fd, "will be able to take care of", $fd, "your stomach when you are", $fd, "getting used to it.", $fe
.ends
.bank 7 slot 2
.section "Script1dba8" free
Script1dba8: .asc "The drive of the sloppy is", $fd, "easy to get rid of, so let's", $fd, "take a look at the drive when", $fd, "it is used.", $fe
.ends
.bank 7 slot 2
.section "Script1dbed" free
Script1dbed: .asc "Because you have an easy-going", $fd, "sickness, let's take a look at", $fd, "the children's pop-ups from", $fd, "the shade of the car, and try", $fd, "to focus on the shincho.", $fe
.ends
.bank 7 slot 2
.section "Script1dc37" free
Script1dc37: .asc "Don't look at the swords or", $fd, "hail, and make sure you don't", $fd, "sacrifice any sedation or", $fd, "sickness.", $fe
.ends
.bank 7 slot 2
.section "Script1dc79" free
Script1dc79: .asc "For more than just shaking,", $fd, "let's keep the speed down, and", $fd, "always keep your heart in mind", $fd, "and keep your heart in mind.", $fe
.ends
.bank 7 slot 2
.section "Script1dcc0" free
Script1dcc0: .asc "Let's start from the heart so", $fd, "that you can fight in the", $fd, "worst places where it is", $fd, "small, and you can fight", $fd, "without rushing.", $fe
.ends
.bank 7 slot 2
.section "Script1dd09" free
Script1dd09: .asc "Since you can do a little bit", $fd, "of things, always try to", $fd, "settle down and make sure to", $fd, "do what you want.", $fe
.ends
.bank 7 slot 2
.section "Script1dd52" free
Script1dd52: .asc "Don't panic or panic if you're", $fd, "behind a car, try to keep your", $fd, "tempo and settle down.", $fe
.ends
.bank 7 slot 2
.section "Script1dd97" free
Script1dd97: .asc "Always keep your heart on the", $fd, "fast track, so that you don't", $fd, "get frustrated or panicked,", $fd, "let's get too fast.", $fe
.ends
.bank 7 slot 2
.section "Script1dde2" free
Script1dde2: .asc "Advice", $fe
.ends
.bank 7 slot 2
.section "Script1dde8" free
Script1dde8: .asc "This is the end of the test.", $fe
.ends
.bank 7 slot 2
.section "Script1ddf6" free
Script1ddf6: .asc "Please choose a game.", $fd, $ff, "    Driving Sense Test", $fd, "    You Are The Best Driver", $fd, "    Pyongkichi Adventure", $fe
.ends
.bank 7 slot 2
.section "Script1de3b" free
Script1de3b: .asc "You are a very good driver.", $fd, "  Let's put our hearts on", $fd, "this one.", $fe
.ends
.bank 7 slot 2
.section "Script1de70" free
Script1de70: .asc "You are a Yuushi Yuuna driver.", $fd, "From now on, let's keep your", $fd, "heart going.", $fe
.ends
.bank 7 slot 2
.section "Script1dea2" free
Script1dea2: .asc "You are a real driver.", $fd, "From now on, let's keep in", $fd, "mind the speed and safety.", $fe
.ends
.bank 7 slot 2
.section "Script1dee4" free
Script1dee4: .asc "You are the average driver.", $fd, "But, the operation of when", $fd, "you're tired, let's reason", $fd, "Bunchi significance.", $fe
.ends
  PatchW $2d2e Script2ca4
  PatchW $2d36 Script2d50
  PatchW $2d3e Script1dde2
  PatchW $2d46 Script1dde8
  PatchW $2d4e Script1ddf6
  PatchW $1de31 Script1de3b
  PatchW $1de33 Script1de70
  PatchW $1de35 Script1dea2
  PatchW $1de37 Script1dee4
  PatchW $1de39 Script1db16
  PatchW $1da44 Script1da5e
  PatchW $1da46 Script1da96
  PatchW $1da48 Script1dace
  PatchW $1da4a Script1db16
  PatchW $1da4c Script1db60
  PatchW $1da4e Script1dbed
  PatchW $1da50 Script1dc37
  PatchW $1da52 Script1dcc0
  PatchW $1da54 Script1dd52
  PatchW $1da56 Script1dba8
  PatchW $1da58 Script1dc79
  PatchW $1da5a Script1dd09
  PatchW $1da5c Script1dd97
  PatchW $5866 Script1da14
  PatchW $586a Script1da1d
  PatchW $586e Script1da26
  PatchW $5872 Script1da2e
  PatchW $5876 Script1da3a
  PatchW $1dfb5 Script1d398
  PatchW $1dfb9 Script1d522
  PatchW $1dfbd Script1d3a1
  PatchW $1dfc1 Script1d56b
  PatchW $1dfc5 Script1d3a9
  PatchW $1dfc9 Script1d5b6
  PatchW $1dfcd Script1d3b5
  PatchW $1dfd1 Script1d60f
  PatchW $1dfe0 Script1d3d8
  PatchW $1dfe4 Script1d3ea
  PatchW $1dfe8 Script1d3e1
  PatchW $1dfec Script1d3bf
  PatchW $1dff1 Script1d3ea
  PatchW $1dff5 Script1d3f1
  PatchW $1dff9 Script1d3bf
  PatchW $1dffe Script1d3fb
  PatchW $1e002 Script1d3ea
  PatchW $1e006 Script1d3bf
  PatchW $1e00b Script1d404
  PatchW $1e00f Script1d404
  PatchW $1e013 Script1d404
  PatchW $1e017 Script1d3bf
  PatchW $1e01c Script1d3fb
  PatchW $1e020 Script1d412
  PatchW $1e024 Script1d418
  PatchW $1e028 Script1d3bf
  PatchW $1e03e Script1d41e
  PatchW $1e042 Script1d428
  PatchW $1e046 Script1d42e
  PatchW $1e04a Script1d439
  PatchW $1e04e Script1d491
  PatchW $1e052 Script1d4f0
  PatchW $1e056 Script1d4fe
  PatchW $1e05a Script1d50f
  PatchW $1e05e Script1d51a
  PatchW $5e55 Script1d668
  PatchW $5ea1 Script1d671
  PatchW $5fa2 Script5fdf
  PatchW $5cc1 Script5c0c
