name: CI

on:
  push:
  pull_request:

jobs:
  build:
    name: build
    runs-on: windows-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
      
    - name: Build
      run: |
        dir
        cd src
        build.cmd
